# Generated by Django 4.2.1 on 2023-12-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="db_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_email", models.CharField(max_length=255)),
                ("db_gender", models.CharField(max_length=125)),
                ("db_country", models.CharField(max_length=255)),
                ("db_phoneNumber", models.CharField(max_length=255)),
                ("db_date_DoB", models.DateField(blank=True)),
                ("auth_token", models.CharField(max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "db_email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="db_Profile_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_email", models.CharField(max_length=255)),
                (
                    "db_photo",
                    models.ImageField(blank=True, max_length=255, upload_to="Profile/"),
                ),
                ("db_bio", models.TextField(default="N/A", max_length=125)),
                (
                    "db_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Authentication.db_profile",
                    ),
                ),
            ],
        ),
    ]
